name: testing workflow variables

on:
  workflow_dispatch:

env:
  cloud: google-cloud

jobs:
  greeting_jobs:
    runs-on: ubuntu-latest
    env:
      greeting: hello
    steps:
      - name: "say hello mona its Monday"
        run: echo "$greeting $FIRST_NAME is using $cloud"
        env:
          FIRST_NAME: Neha
